version: '3.9'

volumes:
  postgres_data:

services:
  db:
    image: postgres:13.3
    ports:
      - 35432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}