"""Registration email is not unique

Revision ID: 20daa8dcadf8
Revises: 16d6dc341519
Create Date: 2022-01-11 01:11:23.574459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20daa8dcadf8'
down_revision = '16d6dc341519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Registrations_email', table_name='Registrations')
    op.create_index(op.f('ix_Registrations_email'), 'Registrations', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Registrations_email'), table_name='Registrations')
    op.create_index('ix_Registrations_email', 'Registrations', ['email'], unique=False)
    # ### end Alembic commands ###
