"""ADD Registrations

Revision ID: 6270cbc9981c
Revises: b4237f3f3f25
Create Date: 2022-01-10 00:34:23.818625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6270cbc9981c'
down_revision = 'b4237f3f3f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Registrations',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_obsolete', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_Registrations_email'), 'Registrations', ['email'], unique=True)
    op.create_index(op.f('ix_Registrations_id'), 'Registrations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Registrations_id'), table_name='Registrations')
    op.drop_index(op.f('ix_Registrations_email'), table_name='Registrations')
    op.drop_table('Registrations')
    # ### end Alembic commands ###
